### PR TITLE
Adding latest AMP Readiness Tool code to amp-bench

### PR DESCRIPTION
**Pull request by philkrie**
@jeffjose 

This pull requests updates the AMP Readiness Tool code to be consistent with the released [extension](https://chrome.google.com/webstore/detail/amp-readiness-tool/fadclbipdhchagpdkjfcpippejnekimg?hl=en).

### CODE REVIEW

**Comment by philkrie** [comment]
@pietergreyling do you mind taking a look and approving?

**Comment by pietergreyling** [comment]
@jeffjose Is the right person to approve for the readiness tool.

**Comment by philkrie** [comment]
Ah... I assumed he couldn't approve since he commented without doing so, I'll ping him :) Thanks!

**Comment by jeffjose** [comment]
Changes LGTM. 

I dont think have permissions to merge the code. @pietergreyling feel free to merge the code when you get a chance. Thanks!

**Comment by philkrie** [comment]
@pietergreyling is there anything missing to get this merged?

**Pull request merged**
