### PR TITLE
Add Bing Ads + branch.io icon (redo)

### PR DESCRIPTION
**Pull request by ithinkihaveacat**
This has the same changes as #46, just rebased on top of master.

This will hopefully: (a) make the diff cleaner; (b) resolve conflicts; and (b) shut googlebot up.

### CODE REVIEW

**Comment by ithinkihaveacat** [comment]
@googlebot CLAs are approved for commit authors @jeffjose (jeffjosejeff@gmail.com) and @philkrie (philkrie@google.com); see discussion in #46.

@jeffjose and @philkire: can you confirm that this PR is what you are expecting?

**Comment by jeffjose** [comment]
LGTM. Please wait for @philkrie to confirm his changes before merging. Thanks!

**Comment by philkrie** [comment]
Looks good to me. Should we merge now or wait to add the full update to use the latest Wappalyzer JSON?

**Comment by jeffjose** [comment]
This PR is now obsolete. We moved readiness-tool from this repo onto ampproject/amp-readiness.

Please feel free to close this PR out WITHOUT merging.

**Pull request closed without merging**
